// @vitest-environment jsdom
import { describe, expect, it } from "vitest";
import { parseSeed } from "./folder";

/* parseSeed is the only pure part of the folder connection, and it is the part
   that touches a file off disk, so it is the part worth testing. */
const REAL = `/* generated by scripts/jobs/export_app.py - do not edit */
window.SEED = {
 "generated": "2026-09-07",
 "from": "you@example.com",
 "counts": {"people": 1, "researched": 0, "named": 1, "companies": 2, "unworked": 0},
 "people": [{"id": "a@b.example", "company": "B"}]
};
`;

describe("reading data.js off disk", () => {
  it("parses the file the exporter actually writes", () => {
    const seed = parseSeed(REAL);
    expect(seed.people).toHaveLength(1);
    expect(seed.generated).toBe("2026-09-07");
  });

  it("parses it rather than evaluating it", () => {
    // A file on your own disk and a file safe to execute are different claims,
    // and only one of them is needed to read a list of people.
    const hostile = 'window.SEED = {"people": [], "counts": {}};\nwindow.stolen = 1;';
    parseSeed(hostile);
    expect((window as unknown as Record<string, unknown>).stolen).toBeUndefined();
  });

  it("refuses a file that is not a seed", () => {
    expect(() => parseSeed("hello")).toThrow();
    expect(() => parseSeed("window.SEED = ")).toThrow();
    expect(() => parseSeed('window.SEED = {"counts": {}}')).toThrow(/no people/);
  });

  it("survives a trailing semicolon, newline and comment", () => {
    expect(parseSeed(REAL + "\n/* trailing */\n").people).toHaveLength(1);
  });
});
